inputs:
  ../scaled_histograms/mumu_nunuww_SM_SM_6TeV.root:
    title: "mumu_nunuww (SM)"
  ../scaled_histograms/mumu_nunuww_SM_6TeV.root:
    title: "mumu_nunuww (EFT model, modified alpha)"
output: results/sm_mod_eft.pdf