inputs:
  ../3/mumu_nunuww_SM_6TeV.root:
    title: "mumu_nunuww SM"
  ../3/ggwpwm_6tev.root:
    title: "ggwpwm"
  ../3/wpwmz_ztonunu_6tev.root:
    title: "wpwmz"
  ../3/wzmunu_6tev.root:
    title: "wzmunu"
  ../3/zzmumu_6tev.root:
    title: "zzmumu"
output: results/reco_3/backgrounds_signal.pdf
normalize: True