inputs:
  ../2/mumu_nunuww_SM_6TeV.root:
    title: "mumu_nunuww SM"
  ../2/ggwpwm_6TeV.root:
    title: "ggwpwm"
  ../2/wpwmz_ztonunu_6TeV.root:
    title: "wpwmz"
  ../2/wzmunu_6TeV.root:
    title: "wzmunu"
  ../2/zzmumu_6TeV.root:
    title: "zzmumu"
output: results/2/backgrounds_signal.pdf