inputs:
  ../2/mumu_nunuww_SM_6TeV.root:
    title: "mumu_nunuww SM"
  ../2/ggwpwm_6tev.root:
    title: "ggwpwm"
  ../2/wpwmz_ztonunu_6tev.root:
    title: "wpwmz"
  ../2/wzmunu_6tev.root:
    title: "wzmunu"
  ../2/zzmumu_6tev.root:
    title: "zzmumu"
output: results/reco_2/backgrounds_signal.pdf
normalize: True