inputs:
  ../all/mumu_nunuww_SM_6TeV.root:
    title: "mumu_nunuww SM"
  ../all/ggwpwm_6tev.root:
    title: "ggwpwm"
  ../all/wpwmz_ztonunu_6tev.root:
    title: "wpwmz"
  ../all/wzmunu_6tev.root:
    title: "wzmunu"
  ../all/zzmumu_6tev.root:
    title: "zzmumu"
output: results/reco_all/backgrounds_signal_xs.pdf
normalize: False